name = "AMQPClient"
uuid = "79c8b4cd-a41a-55fa-907c-fab5288e1383"
keywords = ["amqpclient", "rabbitmq", "amqp", "amqp-client", "message-queue"]
license = "MIT"
desc = "A Julia AMQP (Advanced Message Queuing Protocol) / RabbitMQ Client."
version = "0.3.1"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
